- _includes/head.html
- _includes/navigation.html
- _layouts/default.html
- _sass/_pattern_card.scss
- _sass/main.scss
- index.html
- install.html
- Created the /install page
- Structured the site to have a common navigation
- Added the OS detection to the tabed install instructions
- Go to /install
- Check it matches [the copydoc](https://docs.google.com/document/d/1u8j5uN5d8qSEPDAjA03CGLeTJGf2p2MnHaKARkVmy7w/edit#heading=h.nel9e5tlwcfr)
- Check it [matches the design](https://camo.zenhubusercontent.com/79d4720049bfd269fc3b0beaa346535489f8f839/68747470733a2f2f757365722d696d616765732e67697468756275736572636f6e74656e742e636f6d2f393130353939392f35363336343733302d33343062333438302d363165372d313165392d393663372d6232363337653165643235392e706e67) _Agreed to change the instructions section to grey with hover and active state cards_
- Click on the different OS installs and check it jumps to the instructions about them
- Check loading the …
> Build install page

- install.html
Added a snapcraft badge on install page for linux
- Go to /install
- Select linux (for not already selected)
- See the snapcraft badge looks good and links to the correct snap
Fixes https://github.com/canonical-web-and-design/multipass.run/issues/26
> Add snapcraft badge on install page

- index.html
- js/installversion.js
Skip the prerelease releases when generating the download link 
_Drive by_: Small copy update from the [copy doc](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit?ts=5cdd0e58#)
- Check the homepage
- See that the download buttons link to v1.6.0 instead of v1.7.0
Fixes https://github.com/canonical-web-and-design/multipass.run/issues/35
> Skip the prerelease releases when generating the download link

- index.html
Added system requirements to the "Install Multipass" section
- Run the site using the command ./run serve
- View the site locally in your web browser at: http://127.0.0.1:8026
- Run through the following QA steps
- Please ensure the changes are reflected on the takeover:
- The system requirements are included as specified in the [issue](https://github.com/canonical-web-and-design/multipass.run/issues/42)
Fixes #42
> Add system requirements to download area

- _includes/head.html
- index.html
- Defer `installversion`, `osselector` & `copytoclipboard` scripts and move them to `head`
##QA
- Go to http://0.0.0.0:8026/ and check if it works as expected
Fixes #53
> Defer scripts and move them to head

- nginx.conf
Remove useless redirect due to a copy paste.
Add `/_status/check`  endpoint
- `./run`
- http://0.0.0.0:8026/apps should return 404
- http://0.0.0.0:8026/scopes should return 404
- http://0.0.0.0:8026/_status/check should return `OK`
> Remove useless redirect

- static/latest-release.json
- update.json
- update.yaml
- webapp/app.py
This builds on https://github.com/canonical-web-and-design/multipass.run/pull/62, which introduced this format but doesn't actually work.
I'm only including a JSON endpoint because:
> @Saviq, @ricab: actually, could I suggest that json is a better format for this?
> 
> Firstly, because it's intended to be consumed by code, not by humans, so it's really more of an API. JSON is the common interchange format for APIs.
> 
> But also, it's actually kinda more user friendly, in that if we serve /update.json with a application/json content-type (as we should), most browser will at least display that as text, and some (Firefox) will present it quite nicely.
> 
> ![image](https://user-images.githubusercontent.com/519935/70530052-eebabf00-1b49-11ea-8bf4-bedeacbabda4.png)
> 
> Whereas all of the …
> Set up /static/latest-release.json

- templates/index.html
The foo and bar terms are meaningless. It makes more sense to use meaningful names. So i used "ubuntu-lts" and "ubuntu-lts-custom".
> Replace foo and bar

- templates/_layouts/default.html
##Done
Add report a bug on product link to footer
- Check out the demo
- Scroll to the footer and check the report a link on Multipass itself is there
Fixes https://github.com/canonical-web-and-design/multipass.run/issues/78
> Add report a bug on product link to footer

- templates/index.html
Resolves #75, the Web site description of the minimum macOS version.
> Minimum macOS version 10.10.3 > 10.12.0

- templates/index.html
Reverts the part of #33 that changed `alt="Windows"` to `alt="Windows logo"`, `alt="macOS"` to `alt="macOS logo"`, and `alt="Linux"` to `alt="Linux logo"`.
[As explained in the HTML spec](https://html.spec.whatwg.org/multipage/images.html#a-short-phrase-or-label-with-an-alternative-graphical-representation:-icons,-logos): “If the logo is being used to represent the entity, e.g. as a page heading, the `alt` attribute must contain the name of the entity being represented by the logo. The `alt` attribute must _not_ contain text like the word "logo", as it is not the fact that it is a logo that is being conveyed, it's the entity itself.”
[Discovered while designing #55.]
> Corrects alt= text for OS logos

- webapp/app.py
Set no cache headers for `static/latest-release.json`.
dotrun
browse `static/latest-release.json` and see `Cache-Control: no-store`
> Don't cache latest-release.json

- .env
- templates/_layouts/default.html
multipass has been running on the ubuntu.com GTM container, which is fine, just confusing.
Moving it to its own container with the same tracking.
1. Download this branch
2. Run the site
3. See that the new GTM is linked in - GTM-WTCRZD7
> Update site to new GTM container

- templates/_layouts/default.html
- templates/index.html
- webapp/app.py
- Use lastest-release.json to redirect to latest releases via /download/<os> route
1. download this branch
2. go to http://0.0.0.0:8026/download/macos - see that it starts the latest macos download from github
3. go to http://0.0.0.0:8026/download/windows - see that it starts the latest windows download from github
4. go to http://0.0.0.0:8026/download/turkey and see that it loads the homepage (could change the URL in the browser too?)
> Use lastest-release.json to redirect to latest releases

- package.json
- static/sass/main.scss
- templates/_layouts/default.html
- yarn.lock
- Integrate cookie policy 3.0.4
- Pull the branch
- Run the site using the dotrun snap with `$ dotrun clean` then `$ dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8026/
- Check the cookie policy appears
- Check the manager opens and works
- Make a selection and the notification should disappear
- Scroll to the footer and click the Manage link in the footer
- See that manager appears again. 
Fixes https://github.com/canonical-web-and-design/multipass.run/issues/118
> Integrate cookie-policy v3.0.4

- templates/index.html
-  Add video to `multipass.run`
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8026
- Check the video from the copy doc is visible. It should autoplay from 8s and be 1.5x the speed. 
Fixes #146
> Add embedded media to /multipass.run

- static/latest-release.json
Changing only the url so that https://multipass.run/download/macos points at the bugfixed package.
> Update for a bugfix Multipass 1.8.1

- templates/shared/forms/ubuntu-server-pro-tips.html
Update pro tips cheatsheet
Go to check https://multipass-run-245.demos.haus/ and scroll down to the "Download the cheatsheet"
Fill up the form and download the new cheatsheet (old [cheatsheet](https://assets.ubuntu.com/v1/f401c3f4-Ubuntu_Server_CLI_pro_tips_2020-04.pdf))
Fixes https://github.com/canonical-web-and-design/multipass.run/issues/235
> Update pro tips pdf

- templates/index.html
Removed the link to Freenode at the bottom of the homepage
Check the link has been removed from the homepage
Fixes https://github.com/canonical-web-and-design/multipass.run/issues/262
> Remove Freenode from the community section of the homepage

- package.json
- static/js/docs-side-nav.js
- templates/docs/document.html
- yarn.lock
Updates the side navigation to latest version (as per example in https://github.com/canonical/canonicalwebteam.discourse/pull/143)
Drive-by: upgrade Vanilla to 3.7
Demo: https://multipass-run-267.demos.haus/docs
Visit docs: https://multipass-run-267.demos.haus/docs
Make sure expandable side nav works as expected.
> Update to new version of expandable side nav

- templates/index.html
Section was removed accidentally in the past, so I revived it using https://github.com/canonical/multipass.run/commit/6c29098de633d5b6f459a5ab8faa7e583995b33e
Check https://multipass-run-292.demos.haus/ has the cheatsheet section back, compare with [copy doc](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit?disco=AAAArmTOY2M)
Fixes [WD-2206](https://warthogs.atlassian.net/browse/WD-2206?atlOrigin=eyJpIjoiMzg2MmRmNWMyM2M1NDIzNTk2NjMzMzYyZjgyNjBlNGEiLCJwIjoiaiJ9)
[WD-2206]: https://warthogs.atlassian.net/browse/WD-2206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revive cheat sheet section

- .github/workflows/pr.yaml
- .stylelintrc
- Dockerfile
- package.json
- static/sass/_pattern_github_buttons.scss
- templates/_layouts/default.html
- templates/index.html
- templates/install.html
- templates/partial/_github-buttons.html
- yarn.lock
- Update global nav
- Dotrun github action fixed
- Using `versioned_static` for all scripts.
- Check that https://multipass-run-316.demos.haus/ shows the latest version of global nav
- Top navigation bar is removed and Github links have been moved next to the CTA
- Check https://multipass-run-316.demos.haus/install tabs work correctly
- If you are using MacOS would be nice also to check that the second tab is selected.
Fixes https://github.com/canonical/multipass.run/issues/309
Closes https://warthogs.atlassian.net/browse/WD-7014
> Update global nav

- templates/_layouts/default.html
Update the github issue link so that users can choose an issue type and aren't given a blank form.
> Update github issue link

- package.json
- requirements.txt
- yarn.lock
Bump canonicawebteam.discourse to 5.6.0, vanilla to 4.14.0 and global-nav to 3.6.4
- Check that none of the changes in vanilla have broken anything
- Go to [docs](https://multipass-run-332.demos.haus/docs) and hover over a h2 heading, see the [vanilla anchor link](https://vanillaframework.io/docs/patterns/links#anchor-link) works as expected
- Inspect the heading and see there are no trailing numbers on the heading 
- Expand global nav by clicking "All Canonical" and check that the heading links are white (previously black due to incorrect theming from prev global-nav version)
Fixes [WD-12938](https://warthogs.atlassian.net/browse/WD-12938)
[WD-12938]: https://warthogs.atlassian.net/browse/WD-12938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> chore: Bump canonicawebteam.discourse to 5.6.0, vanilla to 4.14.0 and global-nav to 3.6.4

- requirements.txt
Bump canonicalwebteam.discourse to 5.6.1
- Check that the changes in vanilla have not broken anything
[WD-12938](https://warthogs.atlassian.net/browse/WD-12938)
[WD-12938]: https://warthogs.atlassian.net/browse/WD-12938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-12938 - update canonicalwebteam.discourse to 5.6.1

- README.md
- package.json
- requirements.txt
- webapp/app.py
- yarn.lock
- Upgrade canonicalwebteam.search to 2.1.1
- Upgrade canonicalwebteam.flask-base to 2.0.0
- Pass `app` to `build_search_view()`
- Bump vanilla-framework to 4.16.0
- Go to https://multipass-run-340.demos.haus/docs/search
- Search something
- See rate limit is hit (currently set to 1, so you can search 1 time before hitting it)
Fixes https://warthogs.atlassian.net/browse/WD-15014
> Upgrade canonicalwebteam.search to 2.1.1

- templates/_layouts/default.html
- Call cookie policy script before GTM
- Run the site using the command `./run serve` or `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8026/
- Be sure to test on mobile, tablet and desktop screen sizes
- [List additional steps to QA the new features or prove the bug has been resolved]
Fixes #
[If relevant, please include a screenshot.]
[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)
> Invoke cookie policy before gtm

- static/latest-release.json
For reference: https://github.com/canonical/multipass/releases/tag/v1.14.1
> Update latest-release.json for 1.14.1

- templates/index.html
- Removed a text reference to Hyperkit which was deprecated in Multipass v1.13. Release notes located [here](https://github.com/canonical/multipass/releases/tag/v1.13.0)
> Remove reference to deprecated Multipass backend hypervisor
