- .gitignore
- index.html
Updated the content and styling of the homepage.
- Check that the copy has been updated loosely with the content from the [copy doc](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit#)
- See that the styling is banging!
> Updated the homepage content to match the copy doc

- install.html
- js/copytoclipboard.js
- js/installversion.js
- js/tabs.js
Moved the install page JS to their own scripts
Build a script to pull from GH API and update the install buttons
- Go to /install
- Check the OS tabs work
- Check the copy to clipboard button works
- Check the Windows and Mac download buttons have the correct version and links
_Windows is v0.6.0 and Mac should be v0.6.1_
Fixes https://github.com/canonical-web-and-design/web-squad/issues/772
> Make the download buttons dynamic

- install.html
Fix typo and add a link to using snap documentation.
- Check the code looks correct
- QA if you want
Fixes https://github.com/canonical-web-and-design/multipass.run/issues/28
> Fix typo on the install page

- _layouts/default.html
* Ensure the site is visible in the RT view of the combo tracker :heavy_check_mark:
> Add GA/GTM with the proper config for Optimize

- _includes/footer.html
- _sass/_pattern_separator.scss
- index.html
- js/copytoclipboard.js
1. Download this branch and run the site.
2. See that the migration to vanilla looks ok with spacing variables, the position of the global nav, the copyable code blocks work and the footer looks ok.
> Vanilla 2.3.0 update

- nginx.conf
> Fix nginx conf

- nginx.conf
bad toto bad toto
- `./run build`
- `docker build --build-arg REVISION_ID=test --tag multipass.run .`
- `docker run -ti -p 8004:80 multipass.run`
- http://0.0.0.0:8004/_status/check
> Add missing status code

- update.json
- update.yaml
The purpose of this file is for Multipass to fetch it when checking for updates. It has more data than we can put in GitHub and it allows us to gauge usage.
Included is a .json file for compatibility with our [current code](https://github.com/CanonicalLtd/multipass/blob/20d04c0a770056a90abb0b77c55c6e457003d755/src/platform/update/new_release_monitor.cpp#L69) thats' parsing [GitHub's API](https://api.github.com/repos/CanonicalLtd/multipass/releases/latest).
> Create update.yaml and .json

- .dockerignore
- Dockerfile
- package.json
Use multistage build for docker build
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag multipass.run .`
- `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key multipass.run`
> Update site to use multistage build

- requirements.txt
- templates/docs/document.html
- webapp/app.py
- Update discourse docs
- Update `canonicalwebteam.discourse==4.0.3`
- Add new navigation
- Run the site using the command `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8026/docs
- Check the navigation is working correctly and the content is the [TMP] content
#176
> Update discourse module on multipass

- webapp/app.py
- Update index topic ID to point to correct docs
- run `./dotrun`
- go to `http://0.0.0.0:8026/docs`
-  Check it's pointing to the correct place
> Update index topic id

- templates/sitemap/sitemap-index.xml
- templates/sitemap/sitemap-links.xml
- webapp/app.py
- add sitemap.xml
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8026/sitemap.xml
> Add sitemap

- scripts/linkcheckerrc
Add unsecure localhost to linkchecker ignore
- Check the code looks right.
> Add unsecure localhost to linkchecker ignore

- redirects.yaml
- static/js/tabs.js
- templates/_layouts/default.html
- templates/install.html
- templates/partial/_get-started-linux.html
- templates/partial/_get-started-macos.html
- templates/partial/_get-started-windows.html
- templates/partial/_launch-lts-instances.html
- webapp/app.py
- Build install page
- Remove existing redirect
- Add `install` in the navigation
- Go to https://multipass-run-253.demos.haus/install
- Compare page against [copy doc](https://docs.google.com/document/d/1s_chvwjm3YaGQSmD_StXAwXElh9rsp-BBeFJWk0F7lk/edit#)
Fixes [#5509](https://github.com/canonical-web-and-design/web-squad/issues/5509)
> Build install page

- templates/docs/document.html
- templates/docs/search.html
- Add search to /docs as requested in [this issue](https://github.com/canonical/ubuntu.com/issues/11854)
Go to /docs and test the search function works as expected
Fixes https://github.com/canonical/ubuntu.com/issues/11854
> Add search to /docs

- static/sass/main.scss
Updates how we import vanilla, in order to fix an issue with the nav
> Update how we import vanilla

- templates/shared/forms/ubuntu-server-pro-tips.html
1. Fixed up the Marketo form to work with Marketo
2. Removed the Marketo classes
3. Added a pattern to the email to ensure its valid
- Ensure the changes I have made will resolve the [errors reported](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/32309/)
- Ensure the fields match the [Marketo fields](https://app-sjg.marketo.com/m#FOP3825)
Fixes https://warthogs.atlassian.net/browse/WD-4430
> WD-4430 Fix the contact form

- package.json
- templates/docs/document.html
- yarn.lock
Check https://multipass-run-318.demos.haus/docs/set-up-the-driver has the tabbed content functionality.
> Add RAD support for tabbed docs content

- templates/index.html
- templates/shared/forms/ubuntu-server-pro-tips.html
- Updated cheat sheet link as per [doc](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit#heading=h.yaskb2d6l6px)
- Visit https://multipass-run-323.demos.haus/
- Check that requested change has been made
Fixes https://warthogs.atlassian.net/browse/WD-9821
> Update cheat sheet

- templates/index.html
- templates/shared/forms/ubuntu-server-pro-tips.html
Update cheat sheet according to [copy docs](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit)
- Go to [homepage](https://multipass-run-325.demos.haus/), scroll down to the cheat sheet section 
- Check that [copy doc comments](https://docs.google.com/document/d/1uI5hsuhe5VUpFSSiQas6FVB2F7RhlbNXcr5Pvr_Lm2c/edit) are addressed
Fixes https://warthogs.atlassian.net/browse/WD-10168
> Update cheatsheet for 24.04 release

- package.json
- static/sass/_settings.scss
- static/sass/main.scss
- templates/_layouts/_footer.html
- templates/_layouts/_navigation.html
- templates/_layouts/default.html
- templates/docs/document.html
- templates/index.html
- templates/install.html
- yarn.lock
Migrate to use https://vanillaframework.io/docs/layouts/documentation
> Migrate to new documentation layout

- .github/workflows/pr.yaml
- templates/shared/forms/ubuntu-server-pro-tips.html
Updated firstName field validation for the form not to fail
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8026/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check that the field validation works
Fixes #296  
[WD-11906](https://warthogs.atlassian.net/browse/WD-11906)
[WD-11906]: https://warthogs.atlassian.net/browse/WD-11906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WD-11906 - add name field validation
